addons:
  sonarqube: true
env:
  global:
  - secure: V6eN3DpI1k1yXwjNfIeZXfmlD4ZSUz+qJQbyrvd/5MhDZrwzynOwW6hf/IHRYMMHVThjP3eyQffFf99FYQbihfaUsZxTlRI0IKopaIK7fzOMlNRpeud4qVV7FbRfdYUGrYclrvmvwWCWRqvSzOqdzh11pAC2xpLESFwOqUdel1kRx4UiQf8Z2EAQhKLFfe7o5CRIieJPVBoT54VBCAmx2SQAGLsN2Itx5rSINd2tUzTGvjLpfuO/eSE5ZIBWoSkW/tWu6VSYPOw5TNroRfu+/wdCrAw2DySDLk0x5TpKr2YECejXTnv3498bCF7TX1NTsNIiqJWA4XqtEUDIt5W25ZAjbFIxCHGX0gQxJlnNPN5GDB5u7coeSGVZqq73WUFd57DTVQ+6eYKktWK0Verf/qRIdl+g8Iu3zeuMVG/ieI6NYO0SaTJpDgymgk1h3xaeWcsixJv94cVYG60IVb35+QJlSzR6qnWi+qu5OfNnnJtCwqVSh0worz5/HWuxtNPnrv4TdSmel/ICETP2tzwVGQr24B4JrNEF2h41tJ8XQVNwEDE9JGWVNlyyCszp9wlvfwvC/f2qj84hsCjdGv26Nt2Z1F3xHCoe1EGnhDMTZQIM/c4TpcZAjdSVA+g0qWiRWJ/lvdiZyNUVyHMoMwa5krGoMcmvMFswsH7b/j/x/FM=
language: java
jdk:
- oraclejdk8
script: mvn clean package coveralls:report sonar:sonar -P cobertura -Dsonar.login=$SONAR_TOKEN
